### ISSUE TITLE
NPC Destinations not allowing Citizens to save

### ISSUE THREAD

**Issue by brooklynstarr** [Nutty101/NPC_Destinations2#24]
Hi,

After I enabled NPC Destinations 2.22 on 1.13.1, I found that I was no longer able to save citizens, so any changes I made were lost after stopping/starting the server. After disabling NPC Destinations, I was able to save again. Here is the data I got when I tried to manually save:

Citizens v2.0.24-SNAPSHOT (build 1583)

 >citizens save
 [15:45:35 INFO]: Saving Citizens...
 [15:45:35 WARN]: java.lang.NullPointerException
 [15:45:35 WARN]: at net.livecar.nuttyworks.npc_destinations.citizens.Citizens_Processing.save(Citizens_Processing.java:1380)
 [15:45:35 WARN]: at net.livecar.nuttyworks.npc_destinations.citizens.Citizens_Processing.trait_saveSettings(Citizens_Processing.java:66)
 [15:45:35 WARN]: at net.livecar.nuttyworks.npc_destinations.citizens.NPCDestinationsTrait.save(NPCDestinationsTrait.java:176)
 [15:45:35 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:339)
 [15:45:35 WARN]: at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:154)
 [15:45:35 WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
 [15:45:35 WARN]: at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:441)
 [15:45:35 WARN]: at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:446)
 [15:45:35 WARN]: at net.citizensnpcs.commands.AdminCommands.save(AdminCommands.java:64)
 [15:45:35 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [15:45:35 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 [15:45:35 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 [15:45:35 WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
 [15:45:35 WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
 [15:45:35 WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
 [15:45:35 WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
 [15:45:35 WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)

Thanks.

**Comment by Nutty101** [comment]
This was when it tried to save the blocks that are allowed for the NPC. Odd place to get that error though. Does it continue, or was it just this one time?

**Comment by brooklynstarr** [comment]
It just happens when I run the citizens save command. Citizens does save periodically and at that time I also see the error on the console.

**Comment by brooklynstarr** [comment]
okay so I made some headway. After what McMonkey said, I went through the citizens save file and looked for "allowed blocks." I then changed the values that were no longer valid (for example, Grass in 1.13 is actual grass, not grass block) and changed them to valid values. So for Grass, I changed to Grass_Block. For Brick, I changed to "Bricks" etc. Once I did this, I reloaded citizens and npcdestinations then attempted to save. It saved successfully.

The fix may be to add an update to edit out previous invalid values and replace them with valid ones. Doing it manually may be a pain for some people.

Thanks.

**Comment by Nutty101** [comment]
Ahhh poo! I don't think I wrote anything to convert the block values between versions. It's what I get for doing stuff super quick without thinking about it all. Apologies for that.  I will work on building a conversion for things.

**Comment by brooklynstarr** [comment]
Not a problem, it happens! :) At least we got this sorted out, it was a thorn on my side for weeks.

**Comment by Tiplish** [comment]
Hi, i've this problem too but i've looked in the material part and there is no problem there :s 

The message in console : https://pastebin.com/bHWFPMpE

**Comment by Nutty101** [comment]
@Tiplish The location that it shows says a destination does not have a world for a location (At min the name for it). Can you send me your citizens save.yml? Curious what happened on this one.

**Comment by Tiplish** [comment]
I think i've found the problem. An old NPC was set with a world that we have deleted. Due to 1.14.4, we had temporary deleted a lot of NPC that we usually used. I think that, after respawn all NPC, some of them were from this old world. 

After cleaning the save.yml from that kind of NPC, save work again. Maybe add a protection about that case in the plugin could be helpfull :p

**Comment by Nutty101** [comment]
I will more than likely not do that in the current version 2, but I will in version 3.

**Comment by Nutty101** [comment]
Some protections have been implemented to prevent this more.
