### ISSUE TITLE
Error enabling NpcDestinations

### ISSUE THREAD

**Issue by Gromgrimm** [Nutty101/NPC_Destinations2#45]
[Server thread/INFO]: [NPC_Destinations] BetonQuest found, plugin support enabled (V: 1.12.0-DEV-57)
[09:33:19] [Server thread/ERROR]: Error occurred while enabling NPC_Destinations v2.3.52 (Is it up to date?)
java.lang.NumberFormatException: For input string: "0-DEV-57"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_251]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_251]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_251]
        at net.livecar.nuttyworks.npc_destinations.thirdpartyplugins.betonquest.BetonQuest_Plugin_V1_9.<init>(BetonQuest_Plugin_V1_9.java:20) ~[?:?]
        at net.livecar.nuttyworks.npc_destinations.DestinationsPlugin.onEnable(DestinationsPlugin.java:278) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Nutty101** [comment]
Oops! never expected text in the version. I will get this resolved.

**Comment by Nutty101** [comment]
Resolved in 2.3.54
