### ISSUE TITLE
Setting waypoint provider...."Please report this error [See Console]"

### ISSUE THREAD

**Issue by Jawakotb** [Nutty101/NPC_Destinations2#5]
Just got this when adding a trying to set the /waypoint provider npcdestinations for a new NPC after setting two locations (/nd addlocation <time>)

Error ingame:
Please report this error [See Console]
java.lang.NullPointerException: null

Error on Console:
[19:43:06 INFO]: Fukum issued server command: /nd addlocation sunset
[19:43:14 INFO]: Fukum issued server command: /waypoint provider npcdestinations
[19:43:14 WARN]: java.lang.NullPointerException
[19:43:14 WARN]: 	at net.citizensnpcs.trait.waypoint.LinearWaypointProvider.onRemove(LinearWaypointProvider.java:112)
[19:43:14 WARN]: 	at net.citizensnpcs.trait.waypoint.Waypoints.setWaypointProvider(Waypoints.java:107)
[19:43:14 WARN]: 	at net.citizensnpcs.commands.WaypointCommands.provider(WaypointCommands.java:53)
[19:43:14 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:43:14 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:43:14 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:43:14 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:43:14 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[19:43:14 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[19:43:14 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[19:43:14 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[19:43:14 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:43:14 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:43:14 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[19:43:14 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:43:14 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[19:43:14 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[19:43:14 WARN]: 	at java.lang.Thread.run(Thread.java:745)

Thanks!~

**Comment by Nutty101** [comment]
Odd, let me see whats up with that.

**Comment by Nutty101** [comment]
Do you know what other commands you did between that and create npc?

**Comment by Nutty101** [comment]
Tried for a while to replicate this one, couldn't get it to error out. The errors above are from citizens without showing anything from the plugin. While it's related somehow I think, cannot figure out why. The code that it would hit when adding it really does not care about locations existing etc.
