### ISSUE TITLE
WorldGuard 7.0.4?

### ISSUE THREAD

**Issue by Amadeuss31** [Nutty101/NPC_Destinations2#50]
More of a question than an issue but I had no idea where to ask.
Does this mean it requires WorlsGuard 7.0,3 and not compatible with 7.0.4 beta?

[04:37:57] [Server thread/ERROR]: Could not pass event WorldLoadEvent to NPC_Destinations v2.3.64
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createWorld(CraftServer.java:1076) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:524) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.L(xv:468) ~[?:?]
	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.d(xv:353) ~[?:?]
	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(xv:164) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at com.sk89q.worldguard.WorldGuard.getPlatform(WorldGuard.java:100) ~[?:?]
	at net.livecar.nuttyworks.npc_destinations.worldguard.WorldGuard_7_0_3.getRegionManager(WorldGuard_7_0_3.java:53) ~[?:?]
	at net.livecar.nuttyworks.npc_destinations.worldguard.WorldGuard_7_0_3.onWorldLoad(WorldGuard_7_0_3.java:115) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	... 19 more

Thank you

**Comment by Nutty101** [comment]
I need to update it. I will work on that for you. Thanks for letting me know.

**Comment by Nutty101** [comment]
Should be resolved now.
