### ISSUE TITLE
Sentinel - Causes corrupt save.yml

### ISSUE THREAD

**Issue by Tanjitsu** [Nutty101/NPC_Destinations2#55]
```
[11:34:07] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.28-SNAPSHOT (build 2363)
[11:34:07] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: found undefined alias id098
[11:34:07] [Server thread/WARN]:  in 'string', line 459, column 40:
[11:34:07] [Server thread/WARN]:     ...                targetingHelper: *id098
```

When using  /npcdest info
Then enable the sentinel plugin.
Then set the sentinel of the location.

It stores some data in Citizens save.yml
under....
 npcdestinations:
            PluginSettings:

It then causes the above error when the server is stopped and started again.
There are more errors further down the yaml but that is the first to show.

I was not sure if this needs to be posted in Citizens git or here.
The data is in Citizens.save.yml so i would assume its an issue with their system.
But the data is added to and by the NPCdestinations plugin :D

```[11:29:14] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.28-SNAPSHOT (build 2363)
[11:29:14] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:org.mcmonkey.sentinel.targeting.SentinelTargetingHelper
[11:29:14] [Server thread/WARN]:  in 'string', line 316, column 36:
[11:29:14] [Server thread/WARN]:                       targetingHelper: &id098 !!org.mcmonkey.sentinel.t ... 
[11:29:14] [Server thread/WARN]:                                        ^
[11:29:14] [Server thread/WARN]: 
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[11:29:14] [Server thread/WARN]: 	at Citizens-2.0.28-b2363.jar//net.citizensnpcs.api.util.YamlStorage.load(YamlStorage.java:88)
[11:29:14] [Server thread/WARN]: 	at Citizens-2.0.28-b2363.jar//net.citizensnpcs.Citizens.createStorage(Citizens.java:136)
[11:29:14] [Server thread/WARN]: 	at Citizens-2.0.28-b2363.jar//net.citizensnpcs.Citizens.onEnable(Citizens.java:321)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449)
[11:29:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725)
[11:29:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[11:29:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212)
[11:29:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[11:29:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[11:29:14] [Server thread/WARN]: Caused by: could not determine a constructor for the tag tag:yaml.org,2002:org.mcmonkey.sentinel.targeting.SentinelTargetingHelper
[11:29:14] [Server thread/WARN]:  in 'string', line 316, column 36:
[11:29:14] [Server thread/WARN]:                       targetingHelper: &id098 !!org.mcmonkey.sentinel.t ... 
[11:29:14] [Server thread/WARN]:                                        ^
[11:29:14] [Server thread/WARN]: 
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:574)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[11:29:14] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[11:29:14] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[11:29:14] [Server thread/WARN]: 	... 15 more
[11:29:14] [Server thread/ERROR]: [Citizens] Unable to load saves, disabling...
```

Versions:
```
Server:  paper-1.17.1-243

NPCDestinations-2.6.3
Citizens-2.0.28
Sentinel-2.3.5
```

**Comment by Nutty101** [comment]
Yeah, this is going to be on my side. The issue is that the storage system tries to not duplicate and that is why you get that.  Also, not sure I should even be storing that. I made it generic so I wouldn't have to keep up with all the changes and this is most likely due to that.

**Comment by Nutty101** [comment]
The latest version on Spigot should resolve this for you now.
