### ISSUE TITLE
Internal Error occurred.....   while removing all locations and NPC is "traveling"

### ISSUE THREAD

**Issue by Jawakotb** [Nutty101/NPC_Destinations2#6]
While the NPC is 'traveling', if you try to remove ALL locations that you have set, you see, in game chat, 'an internal error has occurred while attempting to perform this command'.

You also receive the following in console message:
`[00:36:07] [Server thread/INFO]: Fukum issued server command: /nd info
[00:36:18] [Server thread/INFO]: Fukum issued server command: /nd removelocation 0
[00:36:22] [Server thread/INFO]: Fukum issued server command: /nd removelocation 1
[00:36:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nd' in plugin NPC_Destinations v2.01
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f950f8e-622630c]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f950f8e-622630c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-622630c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-622630c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_111]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_111]
	at net.livecar.nuttyworks.npc_destinations.listeners.CommandListener_NPCDest.onCommand(CommandListener_NPCDest.java:1137) ~[?:?]
	at net.livecar.nuttyworks.npc_destinations.DestinationsPlugin.onCommand(DestinationsPlugin.java:266) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f950f8e-622630c]
	... 15 more`

**Comment by Nutty101** [comment]
Fixed, location 1 didn't really exist. Since you removed location 0, loc 1 became 0. Seems that I forgot to check if that location still existed. :(

Thanks for the reports btw, really appreciate them.
