### ISSUE TITLE
Farmer Addon 2.2 NPC not move

### ISSUE THREAD

**Issue by ltsquellette** [Nutty101/NPC_Destinations2#8]
Hello, I am trying to create a NPC in order to plant crops only. I don't know how to make the NPC move and plant crops. I tried to set the center of the field as the position "0" and then use the locmax command to set a range for the npc to replant.

I have used the locfarm command :

![2017-07-23_17 34 57](https://user-images.githubusercontent.com/29739865/28500813-87d1c608-6fcf-11e7-93a9-5edec6a0d211.png)

And i tried to create a path :
![2017-07-23_17 34 43](https://user-images.githubusercontent.com/29739865/28500822-a92595a0-6fcf-11e7-90f0-edec51acfcdf.png)

Finally there is this result :
![2017-07-23_17 34 37](https://user-images.githubusercontent.com/29739865/28500825-b7f3d290-6fcf-11e7-9694-4b9da0d5002e.png)

The NPC seems to be ready to plant but he don't move even if I go far away from him.
I don't know if the carrot I gave to the NPC via /npc equip will be used to replant carrots.
I am sorry for my bad english, I am not an English man. 

Thanks for helping me with this and have a nice day !

**Comment by Nutty101** [comment]
Not a problem on the english, shouldn't have to say sorry for that. World is vast  :)

So with the farmer addon, you really only need the one location, the plugin will do the rest on it's own.

so for a fresh npc, it should be like this.

/npc create Nasus
/nd autoset
/nd addlocation sunrise
/nd locfarmer 0 20 replant

That should do it.

**Comment by ltsquellette** [comment]
Really thank you, it is working perfectly ! :)
I just have some more questions. Why we had to add "sunrise" on addlocation command? Does this mean that time will be set on sunrise when the npc reach his location? 
Then I need to know where we can configure the NPC to replant ONLY and not to harvest then replant.
Finally, is this possible to disable pause4players? In order to force the NPC to plant even if there are players near him.

Thanks a lot for your previous help, hope all goes good for you !

**Comment by ltsquellette** [comment]
In the first time, Nasus have replanted and harvested crops, no problem.
Then he started to stop replant the south east corner of the field and he tried several times to escape the field in order to go in the north west corner.
Then i used /npc equip and /npc look on him.
He stopped work and my console got spammed every second by this message :

[13:25:36] [Server thread/INFO]: [NPCDestinations_Farmer] Error:java.lang.NullPointerException

	at net.livecar.nuttyworks.destinations_farmer.plugin.Farmer_Processing.pluginTick(Farmer_Processing.java:42)

	at net.livecar.nuttyworks.destinations_farmer.DestFarmer_Plugin$1.run(DestFarmer_Plugin.java:74)

	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)

	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)

	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)

	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)

	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)

	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)

	at java.lang.Thread.run(Thread.java:745)

[13:25:37] [Server thread/INFO]: [NPCDestinations_Farmer] Error:java.lang.NullPointerException

	at net.livecar.nuttyworks.destinations_farmer.plugin.Farmer_Processing.pluginTick(Farmer_Processing.java:42)

	at net.livecar.nuttyworks.destinations_farmer.DestFarmer_Plugin$1.run(DestFarmer_Plugin.java:74)

	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)

	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)

	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)

	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)

	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)

	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)

	at java.lang.Thread.run(Thread.java:745)

Thanks for watching this.

**Comment by Nutty101** [comment]
Click the pause for player text, and put a zero in there. That will keep it from pausing at all.

Will look at the errors later today. :)

**Comment by Nutty101** [comment]
So strange, the error is acting like the NPC does not exist anymore. Released 2.3, let me know if that helps the errors.

**Comment by ltsquellette** [comment]
Yes, the update perfectly works ! The error diseapeared, you done a good job, thanks for this version ! 👍 
Can you tell me where i can set Nasus to replant crops only and not harvest them. (Just plant carrots on soil)

And also i got a problem, i set the locmax to 250 from the center (Bedrock) of the field and Nasus don't want to replant the border of the field like this : 

![2017-07-26_21 36 20](https://user-images.githubusercontent.com/29739865/28640428-f34f10d8-724b-11e7-8101-057838716182.png)

Thanks for reading this and have a good evening !

**Comment by Nutty101** [comment]
Odd, I bet i have something wacky with it. I tend to use region's but that should still work the same. Give me a little bit of time, and I will get a fix out there.

I don't know that I ever had it so they wouldn't harvest the crops. Let me look at making it an option to prevent that.

**Comment by Nutty101** [comment]
Btw, worked on this for about 15 minutes, still going just no time :(  Have not forgot about you though :)

**Comment by ltsquellette** [comment]
No worry, take your time ;)

**Comment by Evewins** [comment]
Hi, I'm sorry but I can't find a guide about this plugin, my farmer NPC works but how do I make him put the plants he harvested in a chest or just "access" to his inventory please ?
Thanks

**Comment by Nutty101** [comment]
Oh man, i just saw this. Horrible person I am. You can use Animations to have them unload into a chest.
