### ISSUE TITLE
NPC_Destinations and PlotSquared Bug

### ISSUE THREAD

**Issue by ltsquellette** [Nutty101/NPC_Destinations2#9]
I decided to create a new issue because this will have no link with my previous issue.
Here is the problem : I installed PlotSquared on my server in the last version.
Then the console tells me this : 

[14:06:49] [Server thread/INFO]: [NPC_Destinations] Enabling NPC_Destinations v2.1.11

[14:06:49] [Server thread/INFO]: [NPC_Destinations] MC Version found (MC: 1.11.2)

[14:06:49] [Server thread/INFO]: [NPC_Destinations] Citizens (2.0.21-SNAPSHOT (build 1463)) found, NPC trait enabled.

[14:06:49] [Server thread/INFO]: [NPC_Destinations] BetonQuest not found, quest support disabled

[14:06:49] [Server thread/INFO]: [NPC_Destinations] LightAPI was not found, there will be no support for NPC torch lighting.

[14:06:49] [Server thread/INFO]: [NPC_Destinations] JobsReborn was not found, there will be no support for Jobs in locations.

[14:06:49] [Server thread/INFO]: [NPC_Destinations] Sentinel was not found, there will be no sentinel support in locations.

[14:06:49] [Server thread/INFO]: [NPC_Destinations] PlotSquared found V(), plot compliance supported

[14:06:49] [Server thread/INFO]: [NPC_Destinations] Worldguard found V(6.1.3-SNAPSHOT;c904242), regions supported 

I think there is an error with "plot compliance" because on each world loaded, I get this ERROR : 

[14:06:52] [Server thread/INFO]: Preparing spawn area for Nouveaux, 61%

[14:06:53] [Server thread/ERROR]: Could not pass event WorldLoadEvent to NPC_Destinations v2.1.11

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.createWorld(CraftServer.java:942) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.Bukkit.createWorld(Bukkit.java:469) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466) [Multiverse-Core-2.5.0.jar:?]

	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447) [Multiverse-Core-2.5.0.jar:?]

	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422) [Multiverse-Core-2.5.0.jar:?]

	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725) [Multiverse-Core-2.5.0.jar:?]

	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:312) [Multiverse-Core-2.5.0.jar:?]

	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Caused by: java.lang.NullPointerException

	at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:219) ~[?:?]

	at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:344) ~[?:?]

	at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:211) ~[?:?]

	at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:228) ~[?:?]

	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGuardPlugin.java:1016) ~[?:?]

	at net.livecar.nuttyworks.npc_destinations.worldguard.WorldGuard_Plugin.onWorldLoad(WorldGuard_Plugin.java:94) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]

	... 22 more

To fix it i just had to remove PlotSquared. I don't know if the error come from NPC_Destinations or PlotSquared but I wanted you to know about it.

Hoping this will help someone, have a great day !

**Comment by Nutty101** [comment]
Closing this out. Was addressed in a prior release. Re-open if this issue still exists.
